"use client";

import AppShell from "@/components/layout/AppShell";
import { useMaatruCareDemo, type DemoTimelineEvent } from "@/context/MaatruCareDemoContext";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, CalendarDays, CheckCircle2, Clock3, FileCheck2, FileText, HandHeart, ListChecks, MapPin, ShieldCheck, Sprout, Users, UserRound } from "lucide-react";

const caregivers = [
  { initials: "RR", name: "Rahul Rao", role: "Primary caregiver", color: "bg-[#E8D7E0] text-[#6D3A5B]" },
  { initials: "LR", name: "Lakshmi Rao", role: "Family caregiver", color: "bg-[#E7EEE9] text-[#4F8068]" },
  { initials: "PR", name: "Priya Rao", role: "Support caregiver", color: "bg-[#EEE8E2] text-[#87694A]" },
];

const activities = [
  ["Appointment coordination updated", "Upcoming visit details are confirmed.", "18 min ago", CalendarDays],
  ["Transport responsibility assigned", "Lakshmi is coordinating transport.", "42 min ago", HandHeart],
  ["Care handoff acknowledged", "Appointment coordination is with Lakshmi.", "1 hr ago", CheckCircle2],
  ["Consent permission updated", "Rahul can view approved care updates.", "Yesterday", ShieldCheck],
] as const;

export default function HomePage() {
  const { tasks, handoffs, timeline } = useMaatruCareDemo();
  const openTasks = tasks.filter((task) => task.status === "Open").length;
  const activeHandoffs = handoffs.filter((handoff) => handoff.stage !== "Completed").length;
  const pendingAcknowledgements = handoffs.filter((handoff) => ["Sent", "Reviewed", "Needs review"].includes(handoff.stage)).length;

  return <AppShell><div className="min-w-0 max-w-full overflow-x-hidden pb-3 sm:pb-2">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-[12px] font-medium text-[#9A9196]">Wednesday, September 23</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.03em] text-[#211C1F]">Good morning, Ananya</h1><p className="mt-1.5 text-[13px] text-[#756D72] sm:mt-2 sm:text-sm">Your care, connected.</p></div><div className="flex w-fit items-center gap-2 rounded-full border border-[#E9E1E4] bg-white px-3 py-2 text-[10px] font-semibold text-[#756D72] sm:px-3.5"><ShieldCheck size={14} className="text-[#6D3A5B]" />Patient-controlled care</div></header>
    <section className="mt-6 rounded-[22px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:mt-8 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Journey status</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Your motherhood journey</h2></div><Link href="/journey" className="flex min-h-10 items-center gap-1.5 text-[11px] font-semibold text-[#6D3A5B]">View journey <ArrowUpRight size={13} /></Link></div><div className="relative mt-6 grid grid-cols-2 gap-3 sm:mt-8 sm:grid-cols-4 sm:gap-4"><div className="absolute left-[10%] right-[10%] top-4 hidden h-px bg-[#E9E1E4] sm:block" /><div className="absolute left-[10%] top-4 hidden h-px w-[27%] bg-[#6D3A5B] sm:block" />{["Preconception", "Pregnancy", "Postnatal", "Early motherhood"].map((phase, index) => <div key={phase} className="relative z-10 text-center"><div className={`mx-auto flex h-8 w-8 items-center justify-center rounded-full border-[3px] bg-white ${index === 0 ? "border-[#6D3A5B] bg-[#6D3A5B] text-white" : index === 1 ? "border-[#6D3A5B] shadow-[0_0_0_5px_rgba(109,58,91,0.08)]" : "border-[#E9E1E4]"}`}>{index === 0 ? <CheckCircle2 size={13} /> : index === 1 ? <span className="h-2 w-2 rounded-full bg-[#6D3A5B]" /> : <span className="h-1.5 w-1.5 rounded-full bg-[#D5CDD1]" />}</div><p className={`mt-3 text-[11px] font-semibold ${index === 1 ? "text-[#6D3A5B]" : index === 0 ? "text-[#211C1F]" : "text-[#9A9196]"}`}>{phase}</p><p className="mt-1 text-[9px] text-[#9A9196]">{index === 0 ? "Completed" : index === 1 ? "Current phase" : "Upcoming"}</p></div>)}</div></section>
    <div className="mt-5 grid gap-5 xl:mt-6 xl:grid-cols-[1.1fr_0.9fr]"><AppointmentCard /><CareCircleCard /></div>
    <section className="mt-5 rounded-[20px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:mt-6 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Today&apos;s coordination</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">What needs attention</h2></div><div className="flex flex-wrap gap-2"><Link href="/tasks" className="rounded-[11px] border border-[#E9E1E4] px-3 py-2 text-[10px] font-semibold text-[#6D3A5B]">View tasks</Link><Link href="/handoffs" className="rounded-[11px] border border-[#E9E1E4] px-3 py-2 text-[10px] font-semibold text-[#6D3A5B]">View handoffs</Link></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={<ListChecks size={17} />} label="Open tasks" value={String(openTasks)} /><Metric icon={<HandHeart size={17} />} label="Active handoffs" value={String(activeHandoffs)} /><Metric icon={<Clock3 size={17} />} label="Pending acknowledgements" value={String(pendingAcknowledgements)} /></div></section>
    <div className="mt-5 grid gap-5 lg:mt-6 lg:grid-cols-2"><CareStatus /><Activity events={timeline} /></div>
    <section className="mt-5 rounded-[20px] border border-[#E4D7DF] bg-[#F8F2F6] p-4 sm:mt-6 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Care coordination insight</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Care coordination</h2><p className="mt-2 text-[11px] leading-5 text-[#756D72] sm:text-xs">Your upcoming appointment has assigned responsibilities across your Care Circle.</p></div><div className="grid grid-cols-3 gap-2 sm:gap-3"><SmallMetric label="Caregivers" value="3" /><SmallMetric label="Coordination tasks" value={String(tasks.length)} /><SmallMetric label="Active handoff" value={String(activeHandoffs)} /></div></div></section>
    <section className="mt-5 rounded-[20px] border border-[#E9E1E4] bg-white p-4 sm:mt-6 sm:p-6"><div className="flex items-center gap-3"><Sprout size={18} className="text-[#6D3A5B]" /><h2 className="text-[17px] font-semibold text-[#211C1F]">Quick actions</h2></div><div className="mt-4 grid gap-2.5 sm:grid-cols-2 sm:gap-3 xl:grid-cols-4"><QuickAction href="/tasks" icon={<ListChecks size={17} />} label="Create task" /><QuickAction href="/handoffs" icon={<HandHeart size={17} />} label="Prepare handoff" /><QuickAction href="/consent" icon={<ShieldCheck size={17} />} label="Review consent" /><QuickAction href="/ai-assist" icon={<FileCheck2 size={17} />} label="AI Assist" /></div></section>
    <div className="mt-5 flex gap-3 rounded-[16px] bg-[#FBF8F7] p-3.5 sm:mt-6 sm:p-4"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-[#6D3A5B]" /><p className="text-[11px] leading-5 text-[#756D72]">MaatruCare helps coordinate care, responsibilities and approved information. It does not diagnose conditions, predict medical risk, recommend treatment, or make clinical decisions.</p></div>
  </div></AppShell>;
}

function AppointmentCard() { return <section className="rounded-[22px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Next appointment</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Clinic visit</h2></div><CalendarDays size={18} className="text-[#6D3A5B]" /></div><div className="mt-4 flex items-center gap-3 sm:mt-5 sm:gap-4"><div className="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-[15px] bg-[#6D3A5B] text-white sm:h-16 sm:w-16"><span className="text-[10px] uppercase opacity-80">Sep</span><span className="text-xl font-semibold sm:text-2xl">28</span></div><div><p className="text-[13px] font-semibold text-[#211C1F] sm:text-sm">Monday, 28 September</p><p className="mt-1 flex items-center gap-1.5 text-xs text-[#756D72]"><Clock3 size={13} />10:30 AM</p></div></div><div className="mt-4 flex items-center gap-3 border-t border-[#F0E9EC] pt-4 sm:mt-5 sm:pt-5"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#E8D7E0] text-[#6D3A5B]"><UserRound size={16} /></div><div><p className="text-xs font-semibold text-[#211C1F]">Dr. Meera Sharma</p><p className="mt-1 text-[10px] text-[#9A9196]">City Women&apos;s Clinic</p></div></div><div className="mt-4 grid gap-2 sm:mt-5 sm:grid-cols-2"><CoordinationLine label="Transport" status="Confirmed" good /><CoordinationLine label="Documents" status="Open" /></div><Link href="/appointments" className="mt-4 flex min-h-11 items-center justify-between rounded-[12px] bg-[#6D3A5B] px-4 py-3 text-xs font-semibold text-white sm:mt-5">View appointment <ArrowUpRight size={15} /></Link></section>; }
function CareCircleCard() { return <section className="rounded-[22px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Care Circle</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Trusted people in your care</h2></div><Users size={18} className="text-[#6D3A5B]" /></div><div className="mt-4 space-y-2.5 sm:mt-5 sm:space-y-3">{caregivers.map((caregiver) => <div key={caregiver.name} className="flex min-h-12 items-center gap-3 rounded-[14px] border border-[#F0E9EC] px-3 py-2.5 sm:py-3"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-[10px] font-bold sm:h-10 sm:w-10 ${caregiver.color}`}>{caregiver.initials}</div><div><p className="text-xs font-semibold text-[#211C1F]">{caregiver.name}</p><p className="mt-1 text-[10px] text-[#9A9196]">{caregiver.role}</p></div><CheckCircle2 size={14} className="ml-auto text-[#4F8068]" /></div>)}</div><p className="mt-4 rounded-[14px] bg-[#FBF8F7] p-3 text-[10px] leading-4 text-[#756D72] sm:mt-5">Each caregiver only sees the information and responsibilities you choose to share.</p><Link href="/care-circle" className="mt-3 flex min-h-11 items-center justify-between rounded-[12px] border border-[#E9E1E4] px-4 py-3 text-xs font-semibold text-[#6D3A5B] sm:mt-4">Manage Care Circle <ArrowUpRight size={15} /></Link></section>; }
function CoordinationLine({ label, status, good = false }: { label: string; status: string; good?: boolean }) { return <div className="flex items-center justify-between rounded-[12px] bg-[#FBF8F7] px-3 py-2"><span className="text-[10px] text-[#756D72]">{label}</span><span className={`text-[10px] font-semibold ${good ? "text-[#4F8068]" : "text-[#6D3A5B]"}`}>{status}</span></div>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-[15px] bg-[#FBF8F7] p-3 sm:p-4"><div className="text-[#6D3A5B]">{icon}</div><p className="mt-2 text-2xl font-semibold text-[#211C1F] sm:mt-3">{value}</p><p className="mt-1 text-[10px] leading-4 text-[#756D72]">{label}</p></div>; }
function CareStatus() { return <section className="rounded-[22px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Care status</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Clinician-documented care status</h2></div><FileCheck2 size={18} className="text-[#4F8068]" /></div><div className="mt-4 rounded-[16px] border border-[#DDE9E1] bg-[#F6FAF7] p-3.5 sm:mt-5 sm:p-4"><p className="text-[13px] font-semibold text-[#211C1F] sm:text-sm">Enhanced Observation</p><p className="mt-1 text-[10px] leading-4 text-[#756D72]">This status was explicitly documented by the care team.</p></div><div className="mt-4 flex items-center justify-between gap-4 text-[10px] sm:mt-5"><span className="text-[#9A9196]">Source</span><span className="font-medium text-[#211C1F]">Clinic visit · 22 Sep</span></div><div className="mt-2.5 flex items-center justify-between gap-4 text-[10px] sm:mt-3"><span className="text-[#9A9196]">Status</span><span className="flex items-center gap-1 text-[#4F8068]"><ShieldCheck size={12} />Human verified</span></div><Link href="/profile" className="mt-5 flex items-center justify-between text-[11px] font-semibold text-[#6D3A5B]">View profile <ArrowUpRight size={14} /></Link></section>; }
function Activity({ events }: { events: DemoTimelineEvent[] }) { return <section className="rounded-[22px] border border-[#E9E1E4] bg-white p-4 shadow-[0_8px_30px_rgba(33,28,31,0.035)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#9A9196]">Recent activity</p><h2 className="mt-1 text-[17px] font-semibold text-[#211C1F]">Recent coordination</h2></div><HistoryIcon /></div><div className="mt-4 space-y-3.5 sm:mt-5 sm:space-y-4">{events.slice(0, 4).map((activity, index) => { const Icon = index === 0 ? CalendarDays : index === 1 ? HandHeart : index === 2 ? CheckCircle2 : ShieldCheck; return <div key={activity.id} className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-[10px] bg-[#F3EAF0] text-[#6D3A5B]"><Icon size={15} /></div><div className="min-w-0 flex-1"><div className="flex flex-col gap-0.5 sm:flex-row sm:items-start sm:justify-between sm:gap-3"><p className="text-[11px] font-semibold text-[#211C1F]">{activity.title}</p><span className="shrink-0 text-[9px] text-[#9A9196]">{activity.time}</span></div><p className="mt-1 text-[10px] leading-4 text-[#756D72]">{activity.description}</p></div></div>; })}</div><Link href="/timeline" className="mt-4 flex min-h-11 items-center justify-between border-t border-[#F0E9EC] pt-3 text-[11px] font-semibold text-[#6D3A5B] sm:mt-5 sm:pt-4">View timeline <ArrowUpRight size={14} /></Link></section>; }
function HistoryIcon() { return <Clock3 size={18} className="text-[#9A9196]" />; }
function SmallMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-[14px] bg-white/75 px-2 py-2 text-center sm:px-3"><p className="text-base font-semibold text-[#211C1F] sm:text-lg">{value}</p><p className="mt-1 text-[9px] leading-3.5 text-[#756D72]">{label}</p></div>; }
function QuickAction({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="group flex min-h-14 items-center gap-3 rounded-[14px] border border-[#E9E1E4] bg-white p-3.5 transition hover:-translate-y-0.5 hover:border-[#D7C2CD] sm:p-4"><span className="flex h-9 w-9 items-center justify-center rounded-[10px] bg-[#F3EAF0] text-[#6D3A5B]">{icon}</span><span className="flex-1 text-xs font-semibold text-[#211C1F]">{label}</span><ArrowRight size={14} className="text-[#9A9196] transition group-hover:translate-x-0.5 group-hover:text-[#6D3A5B]" /></Link>; }
